#-----------------------------------------------------------------------
#                       Custom Ground UI Palettes.
#-----------------------------------------------------------------------
# 
# Just paste the new palettes below the dotted line.
# Please check the custom_palettes.txt for further instructions.
#
#-----------------------------------------------------------------------
#                           Palettes Start
#-----------------------------------------------------------------------
			